### ISSUE TITLE
tectonic credentials format

### ISSUE THREAD

**Issue by robgott** [StackPointCloud/stackpoint.io#2]
When trying to add tectonic to a cluster it's asking for a kubernetes secret format of both the universal software licence and the pull secret.

Perhaps the format has changed on the CoreOS site since StackPoint was created, however the USL only shows in "raw format" and the kubernetes secret format of the pull secret is slightly different to what StackPoint is asking for. I tried adapting the secret to match the regex validator used on the StackPoint form fields but it didn't work.  From looking at the logs it seems like the USL worked OK as I can see my account ID in the tectonic logs however it fails to pull the images from quay.io due to auth failure so likely that the pull secret hasn't been picked up.

tectonic site:
```
apiVersion: v1
kind: Secret
metadata:
  name: coreos-pull-secret
data:
  .dockerconfigjson: XXX
type: kubernetes.io/dockerconfigjson
```

StackPoint expects:
```
apiVersion: v1
kind: Secret
metadata:
  name: coreos-pull-secret
data:
  .dockercfg: XXX
type: kubernetes.io/dockercfg
```

USL format I used - but wasn't at all clear that I needed to format it this way:
```
apiVersion: v1
kind: Secret
metadata:  
  name: tectonic-license
data:
  license: {{USL raw format from tectonic site converted to base64}}
type: Opaque
```
